In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker("en_IN")


# Make our dataset reproducible
random.seed(42)
np.random.seed(42)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
print(fake.name())
print(fake.city())
print(fake.state())
print(fake.email())

Omisha Garg
Bhavnagar
Meghalaya
schada@example.org

In [3]:

branches = []

branch_names = [
    "Kolkata Main", "Salt Lake", "Howrah", "Siliguri", "Durgapur",
    "Asansol", "Kharagpur", "Bardhaman", "Naihati", "Barrackpore",
    "Delhi Central", "Noida", "Gurgaon", "Ghaziabad", "Faridabad",
    "Mumbai Central", "Andheri", "Thane", "Navi Mumbai", "Pune",
    "Chennai Central", "Coimbatore", "Madurai", "Hyderabad Central", "Secunderabad",
    "Bengaluru Central", "Mysuru", "Ahmedabad", "Surat", "Vadodara",
    "Jaipur", "Jodhpur", "Lucknow", "Kanpur", "Patna",
    "Bhubaneswar", "Ranchi", "Guwahati", "Kochi", "Thiruvananthapuram",
    "Bhopal", "Indore", "Nagpur", "Raipur", "Chandigarh",
    "Amritsar", "Dehradun", "Varanasi", "Agra", "Visakhapatnam"
]

states = [
    "West Bengal", "West Bengal", "West Bengal", "West Bengal", "West Bengal",
    "West Bengal", "West Bengal", "West Bengal", "West Bengal", "West Bengal",
    "Delhi", "Uttar Pradesh", "Haryana", "Uttar Pradesh", "Haryana",
    "Maharashtra", "Maharashtra", "Maharashtra", "Maharashtra", "Maharashtra",
    "Tamil Nadu", "Tamil Nadu", "Tamil Nadu", "Telangana", "Telangana",
    "Karnataka", "Karnataka", "Gujarat", "Gujarat", "Gujarat",
    "Rajasthan", "Rajasthan", "Uttar Pradesh", "Uttar Pradesh", "Bihar",
    "Odisha", "Jharkhand", "Assam", "Kerala", "Kerala",
    "Madhya Pradesh", "Madhya Pradesh", "Maharashtra", "Chhattisgarh", "Chandigarh",
    "Punjab", "Uttarakhand", "Uttar Pradesh", "Uttar Pradesh", "Andhra Pradesh"
]

for i in range(50):
    branches.append({
        "Branch_ID": f"BR{i+1:03d}",
        "Branch_Name": branch_names[i],
        "State": states[i],
        "City": branch_names[i].replace(" Central", "").replace(" Main", "")
    })

branch_df = pd.DataFrame(branches)

print("Branch table created successfully!")
print("Number of branches:", len(branch_df))

branch_df.head(10)

Branch table created successfully!
Number of branches: 50

  Branch_ID   Branch_Name        State         City
0     BR001  Kolkata Main  West Bengal      Kolkata
1     BR002     Salt Lake  West Bengal    Salt Lake
2     BR003        Howrah  West Bengal       Howrah
3     BR004      Siliguri  West Bengal     Siliguri
4     BR005      Durgapur  West Bengal     Durgapur
5     BR006       Asansol  West Bengal      Asansol
6     BR007     Kharagpur  West Bengal    Kharagpur
7     BR008     Bardhaman  West Bengal    Bardhaman
8     BR009       Naihati  West Bengal      Naihati
9     BR010   Barrackpore  West Bengal  Barrackpore

In [4]:
branch_df

   Branch_ID         Branch_Name           State                City
0      BR001        Kolkata Main     West Bengal             Kolkata
1      BR002           Salt Lake     West Bengal           Salt Lake
2      BR003              Howrah     West Bengal              Howrah
3      BR004            Siliguri     West Bengal            Siliguri
4      BR005            Durgapur     West Bengal            Durgapur
5      BR006             Asansol     West Bengal             Asansol
6      BR007           Kharagpur     West Bengal           Kharagpur
7      BR008           Bardhaman     West Bengal           Bardhaman
8      BR009             Naihati     West Bengal             Naihati
9      BR010         Barrackpore     West Bengal         Barrackpore
10     BR011       Delhi Central           Delhi               Delhi
11     BR012               Noida   Uttar Pradesh               Noida
12     BR013             Gurgaon         Haryana             Gurgaon
13     BR014           Ghaziabad   Uttar Pradesh           Ghaziabad
14     BR015           Faridabad         Haryana           Faridabad
15     BR016      Mumbai Central     Maharashtra              Mumbai
16     BR017             Andheri     Maharashtra             Andheri
17     BR018               Thane     Maharashtra               Thane
18     BR019         Navi Mumbai     Maharashtra         Navi Mumbai
19     BR020                Pune     Maharashtra                Pune
20     BR021     Chennai Central      Tamil Nadu             Chennai
21     BR022          Coimbatore      Tamil Nadu          Coimbatore
22     BR023             Madurai      Tamil Nadu             Madurai
23     BR024   Hyderabad Central       Telangana           Hyderabad
24     BR025        Secunderabad       Telangana        Secunderabad
25     BR026   Bengaluru Central       Karnataka           Bengaluru
26     BR027              Mysuru       Karnataka              Mysuru
27     BR028           Ahmedabad         Gujarat           Ahmedabad
28     BR029               Surat         Gujarat               Surat
29     BR030            Vadodara         Gujarat            Vadodara
30     BR031              Jaipur       Rajasthan              Jaipur
31     BR032             Jodhpur       Rajasthan             Jodhpur
32     BR033             Lucknow   Uttar Pradesh             Lucknow
33     BR034              Kanpur   Uttar Pradesh              Kanpur
34     BR035               Patna           Bihar               Patna
35     BR036         Bhubaneswar          Odisha         Bhubaneswar
36     BR037              Ranchi       Jharkhand              Ranchi
37     BR038            Guwahati           Assam            Guwahati
38     BR039               Kochi          Kerala               Kochi
39     BR040  Thiruvananthapuram          Kerala  Thiruvananthapuram
40     BR041              Bhopal  Madhya Pradesh              Bhopal
41     BR042              Indore  Madhya Pradesh              Indore
42     BR043              Nagpur     Maharashtra              Nagpur
43     BR044              Raipur    Chhattisgarh              Raipur
44     BR045          Chandigarh      Chandigarh          Chandigarh
45     BR046            Amritsar          Punjab            Amritsar
46     BR047            Dehradun     Uttarakhand            Dehradun
47     BR048            Varanasi   Uttar Pradesh            Varanasi
48     BR049                Agra   Uttar Pradesh                Agra
49     BR050       Visakhapatnam  Andhra Pradesh       Visakhapatnam

In [5]:
branch_df.to_csv("../data/branches.csv", index=False)

print("branches.csv saved successfully!")

branches.csv saved successfully!

In [6]:
# ==========================================
# STEP 2: CREATE CUSTOMER TABLE
# ==========================================

customers = []

account_types = [
    "Savings",
    "Current",
    "Salary",
    "Premium Savings"
]

genders = ["Male", "Female"]

occupations = [
    "Salaried",
    "Business",
    "Self Employed",
    "Government Employee",
    "Student",
    "Professional"
]

for i in range(10000):

    customer_id = f"CU{i+1:06d}"

    first_name = fake.first_name()
    last_name = fake.last_name()

    gender = random.choice(genders)

    date_of_birth = fake.date_of_birth(
        minimum_age=21,
        maximum_age=65
    )

    age = (datetime.now().date() - date_of_birth).days // 365

    branch = branch_df.sample(1).iloc[0]

    account_type = random.choice(account_types)

    account_balance = round(
        np.random.lognormal(mean=10, sigma=1),
        2
    )

    credit_score = random.randint(550, 850)

    occupation = random.choice(occupations)

    annual_income = round(
        np.random.uniform(180000, 2500000),
        2
    )

    join_date = fake.date_between(
        start_date="-10y",
        end_date="today"
    )

    customers.append({
        "Customer_ID": customer_id,
        "First_Name": first_name,
        "Last_Name": last_name,
        "Gender": gender,
        "Date_of_Birth": date_of_birth,
        "Age": age,
        "City": branch["City"],
        "State": branch["State"],
        "Branch_ID": branch["Branch_ID"],
        "Account_Type": account_type,
        "Account_Balance": account_balance,
        "Credit_Score": credit_score,
        "Occupation": occupation,
        "Annual_Income": annual_income,
        "Join_Date": join_date
    })

print("Customer data generated successfully!")
print("Number of customers:", len(customers))

Customer data generated successfully!
Number of customers: 10000

In [7]:
# Convert customer list into a Pandas DataFrame

customer_df = pd.DataFrame(customers)

print("Customer DataFrame created successfully!")
print("Rows:", customer_df.shape[0])
print("Columns:", customer_df.shape[1])

customer_df.head()

Customer DataFrame created successfully!
Rows: 10000
Columns: 15

,Customer_ID,First_Name,Last_Name,Gender,Date_of_Birth,Age,City,State,Branch_ID,Account_Type,Account_Balance,Credit_Score,Occupation,Annual_Income,Join_Date
0,CU000001,Yauvani,Oza,Male,1969-10-18,56,Ghaziabad,Uttar Pradesh,BR014,Savings,19144.71,690,Business,715673.68,2025-05-11
1,CU000002,Rachana,Nanda,Male,1969-05-20,57,Kochi,Kerala,BR039,Current,21307.33,602,Professional,1969347.20,2022-06-11
2,CU000003,Anthony,Grover,Male,1999-02-23,27,Mumbai,Maharashtra,BR016,Premium Savings,36368.14,566,Salaried,2201788.57,2018-05-20
3,CU000004,Robert,Kunda,Male,2002-07-11,24,Surat,Gujarat,BR029,Current,70135.66,669,Student,735783.59,2019-09-23
4,CU000005,Dominic,Goda,Male,1991-08-18,35,Noida,Uttar Pradesh,BR012,Current,3981.73,829,Government Employee,2491308.58,2020-11-20

In [8]:
# Check the structure of the customer table

customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      10000 non-null  object
 1   First_Name       10000 non-null  object
 2   Last_Name        10000 non-null  object
 3   Gender           10000 non-null  object
 4   Date_of_Birth    10000 non-null  object
 5   Age              10000 non-null  int64
 6   City             10000 non-null  object
 7   State            10000 non-null  object
 8   Branch_ID        10000 non-null  object
 9   Account_Type     10000 non-null  object
 10  Account_Balance  10000 non-null  float64
 11  Credit_Score     10000 non-null  int64
 12  Occupation       10000 non-null  object
 13  Annual_Income    10000 non-null  float64
 14  Join_Date        10000 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 1.1+ MB

In [9]:
# Check important statistics

customer_df.describe()

                Age  Account_Balance  Credit_Score  Annual_Income
count  10000.000000     1.000000e+04  10000.000000   1.000000e+04
mean      42.969300     3.678256e+04    699.456200   1.338109e+06
std       12.962298     4.846321e+04     87.367302   6.671782e+05
min       21.000000     4.954000e+02    550.000000   1.802670e+05
25%       32.000000     1.131989e+04    623.000000   7.603426e+05
50%       43.000000     2.216693e+04    699.000000   1.335509e+06
75%       54.000000     4.456107e+04    775.000000   1.909599e+06
max       66.000000     1.394289e+06    850.000000   2.499653e+06

In [10]:
# Check for duplicate Customer IDs

duplicate_ids = customer_df["Customer_ID"].duplicated().sum()

print("Duplicate Customer IDs:", duplicate_ids)

Duplicate Customer IDs: 0

In [11]:
# Check missing values

missing_values = customer_df.isnull().sum()

print(missing_values)

Customer_ID        0
First_Name         0
Last_Name          0
Gender             0
Date_of_Birth      0
Age                0
City               0
State              0
Branch_ID          0
Account_Type       0
Account_Balance    0
Credit_Score       0
Occupation         0
Annual_Income      0
Join_Date          0
dtype: int64

In [12]:
# Save customer data to CSV

customer_df.to_csv("../data/customers.csv", index=False)

print("customers.csv saved successfully!")

customers.csv saved successfully!

In [13]:
loans = []

loan_types = [
    "Home Loan",
    "Personal Loan",
    "Car Loan",
    "Education Loan",
    "Business Loan",
    "Gold Loan"
]

for i in range(15000):

    loan_id = f"LN{i+1:06d}"

    customer = customer_df.sample(1).iloc[0]

    customer_id = customer["Customer_ID"]
    branch_id = customer["Branch_ID"]

    loan_type = random.choice(loan_types)

    loan_amount = round(
        np.random.uniform(50000, 5000000),
        2
    )

    interest_rate = round(
        np.random.uniform(7, 18),
        2
    )

    loan_term_months = random.choice([
        12, 24, 36, 48, 60, 84, 120, 180, 240
    ])

    application_date = fake.date_between(
        start_date="-5y",
        end_date="today"
    )

    approval_date = application_date + timedelta(
        days=random.randint(1, 30)
    )

    # Calculate realistic default risk
    risk_score = 0

    if customer["Credit_Score"] < 600:
        risk_score += 3
    elif customer["Credit_Score"] < 700:
        risk_score += 1

    if customer["Annual_Income"] < 400000:
        risk_score += 2

    if loan_amount > customer["Annual_Income"] * 2:
        risk_score += 2

    if interest_rate > 14:
        risk_score += 1

    # Convert risk score into default probability
    default_probability = min(
        0.05 + risk_score * 0.08,
        0.80
    )

    default_flag = (
        1 if random.random() < default_probability else 0
    )

    if default_flag == 1:
        loan_status = "Defaulted"
    else:
        loan_status = random.choice([
            "Active",
            "Closed",
            "Pending"
        ])

    loans.append({
        "Loan_ID": loan_id,
        "Customer_ID": customer_id,
        "Branch_ID": branch_id,
        "Loan_Type": loan_type,
        "Loan_Amount": loan_amount,
        "Interest_Rate": interest_rate,
        "Loan_Term_Months": loan_term_months,
        "Loan_Status": loan_status,
        "Application_Date": application_date,
        "Approval_Date": approval_date,
        "Default_Flag": default_flag
    })

print("Loan data generated successfully!")
print("Number of loans:", len(loans))

Loan data generated successfully!
Number of loans: 15000

In [14]:
loan_df = pd.DataFrame(loans)

print("Total loans:", len(loan_df))

print("\nDefault Flag:")
print(loan_df["Default_Flag"].value_counts())

print("\nLoan Status:")
print(loan_df["Loan_Status"].value_counts())

Total loans: 15000

Default Flag:
Default_Flag
0    11541
1     3459
Name: count, dtype: int64

Loan Status:
Loan_Status
Pending      3894
Active       3830
Closed       3817
Defaulted    3459
Name: count, dtype: int64

In [15]:
new_default_rate = loan_df["Default_Flag"].mean() * 100

print("New Default Rate:", round(new_default_rate, 2), "%")

New Default Rate: 23.06 %

In [16]:
loan_df = pd.DataFrame(loans)

print("Loan DataFrame created successfully!")
print("Rows:", loan_df.shape[0])
print("Columns:", loan_df.shape[1])

loan_df.head()

Loan DataFrame created successfully!
Rows: 15000
Columns: 11

,Loan_ID,Customer_ID,Branch_ID,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Loan_Status,Application_Date,Approval_Date,Default_Flag
0,LN000001,CU002606,BR010,Home Loan,98758.72,7.43,240,Active,2021-10-21,2021-10-28,0
1,LN000002,CU007430,BR002,Home Loan,3478859.81,11.40,48,Pending,2024-09-30,2024-10-09,0
2,LN000003,CU004791,BR011,Home Loan,719407.30,8.88,36,Pending,2023-07-15,2023-08-09,0
3,LN000004,CU008453,BR016,Education Loan,4472474.66,8.43,12,Closed,2022-01-02,2022-01-10,0
4,LN000005,CU004423,BR014,Gold Loan,2493549.04,12.64,84,Defaulted,2023-04-04,2023-04-17,1

In [17]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Loan_ID           15000 non-null  object
 1   Customer_ID       15000 non-null  object
 2   Branch_ID         15000 non-null  object
 3   Loan_Type         15000 non-null  object
 4   Loan_Amount       15000 non-null  float64
 5   Interest_Rate     15000 non-null  float64
 6   Loan_Term_Months  15000 non-null  int64
 7   Loan_Status       15000 non-null  object
 8   Application_Date  15000 non-null  object
 9   Approval_Date     15000 non-null  object
 10  Default_Flag      15000 non-null  int64
dtypes: float64(2), int64(2), object(7)
memory usage: 1.3+ MB

In [18]:
loan_df.describe()

        Loan_Amount  Interest_Rate  Loan_Term_Months  Default_Flag
count  1.500000e+04   15000.000000      15000.000000  15000.000000
mean   2.541714e+06      12.490875         90.672800      0.230600
std    1.419809e+06       3.160957         73.204725      0.421231
min    5.151131e+04       7.000000         12.000000      0.000000
25%    1.322199e+06       9.760000         36.000000      0.000000
50%    2.540291e+06      12.510000         60.000000      0.000000
75%    3.774144e+06      15.240000        120.000000      0.000000
max    4.999807e+06      18.000000        240.000000      1.000000

In [19]:
duplicate_loans = loan_df["Loan_ID"].duplicated().sum()

print("Duplicate Loan IDs:", duplicate_loans)

Duplicate Loan IDs: 0

In [20]:
loan_missing = loan_df.isnull().sum()

print(loan_missing)

Loan_ID             0
Customer_ID         0
Branch_ID           0
Loan_Type           0
Loan_Amount         0
Interest_Rate       0
Loan_Term_Months    0
Loan_Status         0
Application_Date    0
Approval_Date       0
Default_Flag        0
dtype: int64

In [21]:
print(loan_df["Loan_Status"].value_counts())

Loan_Status
Pending      3894
Active       3830
Closed       3817
Defaulted    3459
Name: count, dtype: int64

In [22]:
# Check Default_Flag distribution

print(loan_df["Default_Flag"].value_counts())

Default_Flag
0    11541
1     3459
Name: count, dtype: int64

In [52]:
loan_df.to_csv("../data/loans_ml.csv", index=False)

print("New ML loan dataset saved successfully!")
print("Rows saved:", len(loan_df))

New ML loan dataset saved successfully!
Rows saved: 15000

In [24]:
transactions = []

transaction_types = [
    "Deposit",
    "Withdrawal",
    "Transfer",
    "Payment",
    "UPI",
    "ATM Withdrawal"
]

transaction_modes = [
    "Cash",
    "UPI",
    "Net Banking",
    "Debit Card",
    "Credit Card",
    "ATM"
]

transaction_statuses = [
    "Success",
    "Success",
    "Success",
    "Success",
    "Failed"
]

for i in range(50000):

    transaction_id = f"TX{i+1:06d}"

    # Select a random customer
    customer = customer_df.sample(1).iloc[0]

    customer_id = customer["Customer_ID"]
    branch_id = customer["Branch_ID"]

    transaction_date = fake.date_between(
        start_date="-3y",
        end_date="today"
    )

    transaction_type = random.choice(transaction_types)

    transaction_amount = round(
        np.random.lognormal(mean=8, sigma=1.2),
        2
    )

    transaction_mode = random.choice(transaction_modes)

    transaction_status = random.choice(transaction_statuses)

    transactions.append({
        "Transaction_ID": transaction_id,
        "Customer_ID": customer_id,
        "Branch_ID": branch_id,
        "Transaction_Date": transaction_date,
        "Transaction_Type": transaction_type,
        "Amount": transaction_amount,
        "Transaction_Mode": transaction_mode,
        "Transaction_Status": transaction_status
    })

print("Transaction data generated successfully!")
print("Number of transactions:", len(transactions))

Transaction data generated successfully!
Number of transactions: 50000

In [25]:
transaction_df = pd.DataFrame(transactions)
print("Transaction DataFrame created successfully!")
print("Rows:",transaction_df.shape[0])
print("Columns:",transaction_df.shape[1])
transaction_df.head()

Transaction DataFrame created successfully!
Rows: 50000
Columns: 8

,Transaction_ID,Customer_ID,Branch_ID,Transaction_Date,Transaction_Type,Amount,Transaction_Mode,Transaction_Status
0,TX000001,CU006724,BR005,2025-12-31,UPI,1920.78,Debit Card,Success
1,TX000002,CU000677,BR021,2024-05-23,Payment,4246.14,Net Banking,Success
2,TX000003,CU007867,BR033,2025-08-30,ATM Withdrawal,7428.96,Credit Card,Success
3,TX000004,CU007845,BR021,2025-01-15,Deposit,3139.63,Cash,Success
4,TX000005,CU007344,BR037,2024-01-25,UPI,1508.80,Cash,Success

In [26]:
transaction_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      50000 non-null  object
 1   Customer_ID         50000 non-null  object
 2   Branch_ID           50000 non-null  object
 3   Transaction_Date    50000 non-null  object
 4   Transaction_Type    50000 non-null  object
 5   Amount              50000 non-null  float64
 6   Transaction_Mode    50000 non-null  object
 7   Transaction_Status  50000 non-null  object
dtypes: float64(1), object(7)
memory usage: 3.1+ MB

In [27]:
transaction_df.describe()

              Amount
count   50000.000000
mean     6166.161850
std     10692.578622
min        21.510000
25%      1314.590000
50%      3002.360000
75%      6733.195000
max    306118.220000

In [28]:
duplicate_transactions = transaction_df["Transaction_ID"].duplicated().sum()

print("Duplicate Transaction IDs:", duplicate_transactions)

Duplicate Transaction IDs: 0

In [29]:
transaction_missing = transaction_df.isnull().sum()

print(transaction_missing)

Transaction_ID        0
Customer_ID           0
Branch_ID             0
Transaction_Date      0
Transaction_Type      0
Amount                0
Transaction_Mode      0
Transaction_Status    0
dtype: int64

In [30]:
print(transaction_df["Transaction_Type"].value_counts())

Transaction_Type
Withdrawal        8518
Deposit           8382
Transfer          8313
ATM Withdrawal    8305
Payment           8246
UPI               8236
Name: count, dtype: int64

In [31]:
print(transaction_df["Transaction_Mode"].value_counts())

Transaction_Mode
Net Banking    8407
UPI            8407
ATM            8344
Debit Card     8310
Credit Card    8283
Cash           8249
Name: count, dtype: int64

In [32]:
print(transaction_df["Transaction_Status"].value_counts())

Transaction_Status
Success    39954
Failed     10046
Name: count, dtype: int64

In [33]:
transaction_df.to_csv("../data/transactions.csv", index=False)

print("transactions.csv saved successfully!")

transactions.csv saved successfully!

In [34]:
payments = []

payment_statuses = [
    "Paid",
    "Paid",
    "Paid",
    "Late",
    "Missed"
]

payment_methods = [
    "UPI",
    "Net Banking",
    "Debit Card",
    "Cash",
    "Auto Debit"
]

for i in range(40000):

    payment_id = f"PM{i+1:06d}"

    # Select a random loan
    loan = loan_df.sample(1).iloc[0]

    loan_id = loan["Loan_ID"]
    customer_id = loan["Customer_ID"]
    branch_id = loan["Branch_ID"]

    payment_date = fake.date_between(
        start_date="-3y",
        end_date="today"
    )

    payment_amount = round(
        np.random.uniform(1000, 100000),
        2
    )

    payment_status = random.choice(payment_statuses)

    payment_method = random.choice(payment_methods)

    payments.append({
        "Payment_ID": payment_id,
        "Loan_ID": loan_id,
        "Customer_ID": customer_id,
        "Branch_ID": branch_id,
        "Payment_Date": payment_date,
        "Payment_Amount": payment_amount,
        "Payment_Status": payment_status,
        "Payment_Method": payment_method
    })

print("Payment data generated successfully!")
print("Number of payments:", len(payments))

Payment data generated successfully!
Number of payments: 40000

In [35]:
payment_df = pd.DataFrame(payments)

print("Payment DataFrame created successfully!")
print("Rows:", payment_df.shape[0])
print("Columns:", payment_df.shape[1])

payment_df.head()

Payment DataFrame created successfully!
Rows: 40000
Columns: 8

,Payment_ID,Loan_ID,Customer_ID,Branch_ID,Payment_Date,Payment_Amount,Payment_Status,Payment_Method
0,PM000001,LN012087,CU006468,BR044,2023-12-16,60749.40,Late,UPI
1,PM000002,LN009207,CU005190,BR049,2025-06-27,81869.53,Missed,Auto Debit
2,PM000003,LN004397,CU002811,BR007,2024-08-22,40448.34,Paid,Cash
3,PM000004,LN010020,CU003361,BR025,2024-03-31,87240.26,Paid,Cash
4,PM000005,LN000518,CU002023,BR020,2024-09-12,37291.34,Missed,Auto Debit

In [36]:
payment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      40000 non-null  object
 1   Loan_ID         40000 non-null  object
 2   Customer_ID     40000 non-null  object
 3   Branch_ID       40000 non-null  object
 4   Payment_Date    40000 non-null  object
 5   Payment_Amount  40000 non-null  float64
 6   Payment_Status  40000 non-null  object
 7   Payment_Method  40000 non-null  object
dtypes: float64(1), object(7)
memory usage: 2.4+ MB

In [37]:
payment_df.describe()

       Payment_Amount
count    40000.000000
mean     50556.951529
std      28460.548948
min       1002.240000
25%      25939.047500
50%      50466.780000
75%      74953.455000
max      99995.350000

In [38]:
duplicate_payments = payment_df["Payment_ID"].duplicated().sum()

print("Duplicate Payment IDs:", duplicate_payments)

Duplicate Payment IDs: 0

In [39]:
payment_missing = payment_df.isnull().sum()

print(payment_missing)

Payment_ID        0
Loan_ID           0
Customer_ID       0
Branch_ID         0
Payment_Date      0
Payment_Amount    0
Payment_Status    0
Payment_Method    0
dtype: int64

In [40]:
print(payment_df["Payment_Status"].value_counts())

Payment_Status
Paid      23904
Late       8131
Missed     7965
Name: count, dtype: int64

In [41]:
print(payment_df["Payment_Method"].value_counts())

Payment_Method
Debit Card     8085
Auto Debit     8057
Net Banking    8001
UPI            7967
Cash           7890
Name: count, dtype: int64

In [42]:
payment_df.to_csv("../data/payments.csv", index=False)

print("payments.csv saved successfully!")

payments.csv saved successfully!

In [43]:
print("Branches:", len(branch_df))
print("Customers:", len(customer_df))
print("Loans:", len(loan_df))
print("Transactions:", len(transaction_df))
print("Payments:", len(payment_df))

Branches: 50
Customers: 10000
Loans: 15000
Transactions: 50000
Payments: 40000

In [44]:
invalid_loan_customers = ~loan_df["Customer_ID"].isin(
    customer_df["Customer_ID"]
)

print("Loans with invalid Customer_ID:",
      invalid_loan_customers.sum())

Loans with invalid Customer_ID: 0

In [45]:
invalid_transaction_customers = ~transaction_df["Customer_ID"].isin(
    customer_df["Customer_ID"]
)

print("Transactions with invalid Customer_ID:",
      invalid_transaction_customers.sum())

Transactions with invalid Customer_ID: 0

In [46]:
invalid_payment_loans = ~payment_df["Loan_ID"].isin(
    loan_df["Loan_ID"]
)

print("Payments with invalid Loan_ID:",
      invalid_payment_loans.sum())

Payments with invalid Loan_ID: 0

In [47]:
invalid_loan_branches = ~loan_df["Branch_ID"].isin(
    branch_df["Branch_ID"]
)

print("Loans with invalid Branch_ID:",
      invalid_loan_branches.sum())

Loans with invalid Branch_ID: 0

In [48]:
invalid_transaction_branches = ~transaction_df["Branch_ID"].isin(
    branch_df["Branch_ID"]
)

print("Transactions with invalid Branch_ID:",
      invalid_transaction_branches.sum())

Transactions with invalid Branch_ID: 0

In [49]:
invalid_payment_branches = ~payment_df["Branch_ID"].isin(
    branch_df["Branch_ID"]
)

print("Payments with invalid Branch_ID:",
      invalid_payment_branches.sum())

Payments with invalid Branch_ID: 0

In [50]:
print("Duplicate Branch IDs:",
      branch_df["Branch_ID"].duplicated().sum())

print("Duplicate Customer IDs:",
      customer_df["Customer_ID"].duplicated().sum())

print("Duplicate Loan IDs:",
      loan_df["Loan_ID"].duplicated().sum())

print("Duplicate Transaction IDs:",
      transaction_df["Transaction_ID"].duplicated().sum())

print("Duplicate Payment IDs:",
      payment_df["Payment_ID"].duplicated().sum())

Duplicate Branch IDs: 0
Duplicate Customer IDs: 0
Duplicate Loan IDs: 0
Duplicate Transaction IDs: 0
Duplicate Payment IDs: 0

In [51]:
print("===== DATASET SUMMARY =====")

print("Branches      :", branch_df.shape)
print("Customers     :", customer_df.shape)
print("Loans         :", loan_df.shape)
print("Transactions  :", transaction_df.shape)
print("Payments      :", payment_df.shape)

print("\n===== RELATIONSHIP CHECK =====")

print("All loan customers valid       :",
      (~invalid_loan_customers).all())

print("All transaction customers valid:",
      (~invalid_transaction_customers).all())

print("All payment loans valid        :",
      (~invalid_payment_loans).all())

===== DATASET SUMMARY =====
Branches      : (50, 4)
Customers     : (10000, 15)
Loans         : (15000, 11)
Transactions  : (50000, 8)
Payments      : (40000, 8)

===== RELATIONSHIP CHECK =====
All loan customers valid       : True
All transaction customers valid: True
All payment loans valid        : True